/**
 * Configuration management for Conductor
 * All configuration loaded from environment variables
 */

import { z } from "zod";

const ConfigSchema = z.object({
  port: z.number().default(80),
  databaseUrl: z.string().url(),
  redisUrl: z.string().url(),
  giteaUrl: z.string().url(),
  giteaToken: z.string().default(""),
  gatewayUrl: z.string().url(),
  gatewayApiKey: z.string(),
  mcpGiteaUrl: z.string().url(),
  mcpConductorUrl: z.string().url(),
  mcpSystemUrl: z.string().url(),
  mcpVectorUrl: z.string().url(),
  mcpSonarUrl: z.string().url().optional(),
  webhookSecret: z.string(),
  conductorSecret: z.string(),
  conductorOrg: z.string().default("cuemarshal"),
  conductorRepo: z.string().default("cuemarshal"),
  templateRepoUrl: z.string().url().default("https://raw.githubusercontent.com/CueMarshal/CueMarshal/main"),
  webhookLoopThreshold: z.number().default(10),
  webhookIdempotencyTTL: z.number().default(3600),
  botUsernames: z.string().default("cuemarshal-bot,conductor-bot"),
  chatModel: z.string().default("tier2"),
  decomposeModel: z.string().default("tier2"),
  planningModel: z.string().default("gpt-4o"),
  totalMonthlyBudgetUsd: z.number().default(100),
  selfImproveBudgetPct: z.number().default(10),
  selfImproveMaxPerCycle: z.number().default(3),
  selfImproveCooldownHours: z.number().default(4),
  selfImproveProtectedPaths: z.string().default("conductor/,gateway/,mcp-servers/,infrastructure/"),
  selfImproveFailureThreshold: z.number().int().positive().default(3),
  selfImproveFailureWindowHours: z.number().positive().default(24),
  selfImproveTestMode: z.boolean().default(false),
  modelSelectorTier1Threshold: z.number().default(0.30),
  modelSelectorTier3Threshold: z.number().default(0.70),
  retryMaxTotal: z.number().default(6),
  retryMaxTier1: z.number().default(2),
  retryMaxTier2: z.number().default(2),
  retryMaxTier3: z.number().default(1),
  retryBackoffBaseMs: z.number().default(5000),
  retryBackoffMaxMs: z.number().default(60000),
  retryCooldownMs: z.number().default(10000),
  logLevel: z.enum(["debug", "info", "warn", "error"]).default("info"),
  nodeEnv: z.enum(["development", "production", "test"]).default("production"),
});

export type Config = z.infer<typeof ConfigSchema>;

export function loadConfig(): Config {
  return ConfigSchema.parse({
    port: parseInt(process.env.PORT || "80"),
    databaseUrl: process.env.DATABASE_URL,
    redisUrl: process.env.REDIS_URL,
    giteaUrl: process.env.GITEA_URL,
    giteaToken: process.env.GITEA_TOKEN,
    gatewayUrl: process.env.GATEWAY_URL,
    gatewayApiKey: process.env.GATEWAY_API_KEY,
    mcpGiteaUrl: process.env.MCP_GITEA_URL,
    mcpConductorUrl: process.env.MCP_CONDUCTOR_URL,
    mcpSystemUrl: process.env.MCP_SYSTEM_URL,
    mcpVectorUrl: process.env.MCP_VECTOR_URL,
    mcpSonarUrl: process.env.MCP_SONAR_URL,
    webhookSecret: process.env.WEBHOOK_SECRET,
    conductorSecret: process.env.CONDUCTOR_SECRET,
    conductorOrg: process.env.CONDUCTOR_ORG,
    conductorRepo: process.env.CONDUCTOR_REPO,
    templateRepoUrl: process.env.TEMPLATE_REPO_URL,
    webhookLoopThreshold: parseInt(process.env.WEBHOOK_LOOP_THRESHOLD || "10"),
    webhookIdempotencyTTL: parseInt(process.env.WEBHOOK_IDEMPOTENCY_TTL || "3600"),
    botUsernames: process.env.BOT_USERNAMES,
    chatModel: process.env.CHAT_MODEL,
    decomposeModel: process.env.DECOMPOSE_MODEL,
    planningModel: process.env.PLANNING_MODEL,
    totalMonthlyBudgetUsd: parseFloat(process.env.TOTAL_MONTHLY_BUDGET_USD || "100"),
    selfImproveBudgetPct: parseFloat(process.env.SELF_IMPROVE_BUDGET_PCT || "10"),
    selfImproveMaxPerCycle: parseInt(process.env.SELF_IMPROVE_MAX_PER_CYCLE || "3"),
    selfImproveCooldownHours: parseInt(process.env.SELF_IMPROVE_COOLDOWN_HOURS || "4"),
    selfImproveProtectedPaths: process.env.SELF_IMPROVE_PROTECTED_PATHS,
    selfImproveFailureThreshold: parseInt(process.env.SELF_IMPROVE_FAILURE_THRESHOLD || "3"),
    selfImproveFailureWindowHours: parseFloat(process.env.SELF_IMPROVE_FAILURE_WINDOW_HOURS || "24"),
    selfImproveTestMode: process.env.SELF_IMPROVE_TEST_MODE === "true",
    modelSelectorTier1Threshold: parseFloat(process.env.MODEL_SELECTOR_TIER1_THRESHOLD || "0.30"),
    modelSelectorTier3Threshold: parseFloat(process.env.MODEL_SELECTOR_TIER3_THRESHOLD || "0.70"),
    retryMaxTotal: parseInt(process.env.RETRY_MAX_TOTAL || "6"),
    retryMaxTier1: parseInt(process.env.RETRY_MAX_TIER1 || "2"),
    retryMaxTier2: parseInt(process.env.RETRY_MAX_TIER2 || "2"),
    retryMaxTier3: parseInt(process.env.RETRY_MAX_TIER3 || "1"),
    retryBackoffBaseMs: parseInt(process.env.RETRY_BACKOFF_BASE_MS || "5000"),
    retryBackoffMaxMs: parseInt(process.env.RETRY_BACKOFF_MAX_MS || "60000"),
    retryCooldownMs: parseInt(process.env.RETRY_COOLDOWN_MS || "10000"),
    logLevel: process.env.LOG_LEVEL as any,
    nodeEnv: process.env.NODE_ENV as any,
  });
}

/** Singleton — import this instead of calling loadConfig() each time */
export const config = loadConfig();
