apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cuemarshal.fullname" . }}-oauth-config
  labels:
    {{- include "cuemarshal.labels" . | nindent 4 }}
    component: conductor
data:
  oauth2_client_id: ""
