#!/bin/sh
set -eu

# Reads the OAuth2 client ID generated by init-gitea.sh from the
# Docker volume and patches mobile/app.json before launching the app.

VOLUME_NAME="cuemarshal-gitea-tokens"
TOKEN_FILE="/tokens/oauth2_client_id"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
APP_JSON="${SCRIPT_DIR}/../mobile/app.json"

if [ ! -f "${APP_JSON}" ]; then
  echo "ERROR: ${APP_JSON} not found"
  exit 1
fi

# Read the client ID from the Docker volume
CLIENT_ID=$(docker run --rm -v "${VOLUME_NAME}:${TOKEN_FILE%/*}:ro" alpine cat "${TOKEN_FILE}" 2>/dev/null || true)

if [ -z "${CLIENT_ID}" ]; then
  echo "WARNING: Could not read oauth2_client_id from volume '${VOLUME_NAME}'."
  echo "         Is the stack running and init-gitea completed?"
  echo "         Keeping existing value in app.json."
  exit 0
fi

# Trim whitespace / newlines
CLIENT_ID=$(echo "${CLIENT_ID}" | tr -d '[:space:]')

# Read current value so we can skip a no-op write
CURRENT_ID=$(sed -n 's/.*"oauth2ClientId"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "${APP_JSON}")

if [ "${CURRENT_ID}" = "${CLIENT_ID}" ]; then
  echo "oauth2ClientId already up-to-date (${CLIENT_ID})"
  exit 0
fi

# Portable in-place sed (works on both macOS and Linux)
if sed --version >/dev/null 2>&1; then
  # GNU sed
  sed -i "s/\"oauth2ClientId\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"oauth2ClientId\": \"${CLIENT_ID}\"/" "${APP_JSON}"
else
  # BSD sed (macOS)
  sed -i '' "s/\"oauth2ClientId\"[[:space:]]*:[[:space:]]*\"[^\"]*\"/\"oauth2ClientId\": \"${CLIENT_ID}\"/" "${APP_JSON}"
fi

echo "Updated oauth2ClientId in app.json → ${CLIENT_ID}"
