{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cuemarshal.fullname" . }}-prometheus
  labels:
    {{- include "cuemarshal.labels" . | nindent 4 }}
    component: prometheus
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 9090
    targetPort: http
  selector:
    {{- include "cuemarshal.selectorLabels" . | nindent 4 }}
    component: prometheus
{{- end }}
