apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "cuemarshal.fullname" . }}-tokens
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cuemarshal.labels" . | nindent 4 }}
    component: tokens
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: 100Mi
